version: "3.8"

services:
  nginx:
    image: local-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    networks:
      - nginx-network

  python-app:
    image: local-python-app
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python_app
    expose:
      - "8000"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
